addSbtPlugin("com.eed3si9n"   % "sbt-assembly"           % "2.1.1")
addSbtPlugin("com.github.sbt" % "sbt-native-packager"    % "1.9.13")
addSbtPlugin("org.jmotor.sbt" % "sbt-dependency-updates" % "1.2.9")
addSbtPlugin("io.spray"       % "sbt-revolver"           % "0.10.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"           % "2.5.4")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"          % "0.13.1")
addSbtPlugin("com.github.sbt" % "sbt-javaagent"          % "0.1.8")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"           % "0.14.2")
